org: mrsushi
app: mrsushi-app
service: menu-service

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    MENU_TABLE: ${self:service}-${sls:stage}-MenuTable
  role: arn:aws:iam::${aws:accountId}:role/LabRole

functions:
  getMenu:
    handler: handler.get_menu
    events:
      - http:
          path: menu
          method: get
          cors: true

resources:
  Resources:
    MenuTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.MENU_TABLE}
        AttributeDefinitions:
          - AttributeName: producto_id
            AttributeType: S
        KeySchema:
          - AttributeName: producto_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
